### ISSUE TITLE
How to transfer the YCB dataset to the xml file? 

### ISSUE THREAD

**Issue by happygaoxiao** [vikashplus/YCB_sim#1]
Thanks a lot for your work! I tried to write `.xml` files for others objects in YCB. However, there is always an error for the texture. I download the YCB datasets and replace the strings for the object mesh (`nontextured.stl`) and texture (`texture_map.png`). It doesn't work.

> Exception: Failed to load XML file: ycb_banana.xml. mj_loadXML error: b"Error: PNG size must be integer multiple of gridsize in texture

If I use the `block.png`, it can show well.
![image](https://user-images.githubusercontent.com/24514908/165802928-643edd3c-30e0-45f6-91ae-42d7ed025ffc.png)

 Could you please show me how you write the `.xml` files? Thank you for your help!

**Comment by happygaoxiao** [comment]
Here is part of the `.xml` file:

```
     <asset>
         <texture name="texture:object" file="includes/011_banana/google_16k/texture_map.png"/>
<!--         <texture name="011_banana"  file="includes/011_banana/google_16k/block.png"/>-->
        <mesh name="011_banana"     file="includes/011_banana/google_16k/nontextured.stl"/>
        <material name="011_banana" texture="texture:object"/>
    </asset>
```
Only a part of the banana is covered by texture.
![image](https://user-images.githubusercontent.com/24514908/165805152-753b0322-e06d-49c5-9582-83397ce09bf6.png)

If I add `type="2d"` as you did, only a half of the banana is covered.
![image](https://user-images.githubusercontent.com/24514908/165805414-bf9a31bf-9e6f-446f-bf15-c95764cc7dea.png)

**Comment by tinwech** [comment]
@happygaoxiao hi, have you solved the problem? I'm facing the same issue.
It seems that we need to determine the mapping coordinate, but I don't know how either.

**Comment by happygaoxiao** [comment]
@tinwech Hello, sorry, I haven't solved this problem.

**Comment by tinwech** [comment]
@happygaoxiao Hi, I found the solution. 
Because .stl file does not support textures, it's geometry only (that's why it was named nontextured.stl in ycb dataset)
All you need to do is to use textured.obj instead of nontextured.stl for mesh, that should solve the problem.
You can check out this repo https://github.com/kevinzakka/mujoco_scanned_objects

If your mujoco version does not support .obj file, just transfer .obj file to .msh

**Comment by happygaoxiao** [comment]
Hello, thank you for your help. I use Mujoco 210. Which version are you using for support .obj files? It seems that the repo you posted uses the latest verion?

**Comment by happygaoxiao** [comment]
After updating MuJoCo to 2.3.5, problem is solved.

**Comment by vikashplus** [comment]
@happygaoxiao  -- if you have other models working, please send PR and we can integrate to create a YCB set for MuJoCo. Let me know if this will be of interest.

**Comment by vikashplus** [comment]
btw, here is the likely fix that recently landed https://github.com/deepmind/mujoco/issues/859
