### ISSUE TITLE
How to obtain the *.msh file of YCB object?

### ISSUE THREAD

**Issue by wukongwong** [vikashplus/YCB_sim#2]
I found the mesh file in the folder is msh. but the format in the ycb website is obj or stl.

**Comment by vikashplus** [comment]
msh is mujoco's mesh format. you can read about it here 
https://mujoco.readthedocs.io/en/latest/XMLreference.html?highlight=msh#asset-mesh

**Comment by wukongwong** [comment]
Thanks a lot for your response.
I think you misunderstood me, what I want to do is to import the YCB object
into Mujoco. I found your example mesh file on GitHub in msh format, so I
would like to have other YCB objects' .msh format files, but I cannot get
them directly from the official website of YCB-dataset. They only provide
.obj format or .stl format, so my question is how to obtain the msh format
of other YCB objects.
Thanks again for your help!

**Comment by vikashplus** [comment]
I'm not sure if there is an official convertor. One might have to write one themselves. I wrote a small script (non-public) to convert some from the obj files.
