### ISSUE TITLE
Visualization mesh geoms have mass

### ISSUE THREAD

**Issue by Balint-H** [vikashplus/YCB_sim#5]
Spotted in MuJoCo 3.1.2

Including the visualization meshes in the objects increases their mass. 

Here's the contact forces with the ground with both collision geom and viz mesh (also notice the asymmetrical forces due to non centred CoM):
![image](https://github.com/user-attachments/assets/eea0d6e1-cd88-42ba-8231-0ac17c4bbcd0)

And here it is with only collision: 
![image](https://github.com/user-attachments/assets/af688746-90fb-4559-8e9b-ed4bc8084d14)

Simply adding mass=0 to the viz class resolves this.

**Comment by vikashplus** [comment]
Can you add the XML that was used to generate this model?

**Comment by Balint-H** [comment]
It is reproducible from the example xml:

https://github.com/vikashplus/YCB_sim/blob/main/ycb_objects.xml

The object's have more mass and are heavier than they should be from their collision geoms.

And then e.g. object 009's visual geom can be removed and the scene reloaded to see the change.

**Comment by vikashplus** [comment]
Thanks for catching the bug. Fixed here 4619e915e80c615950e2b5d3a09f29f450545b0d
